### ISSUE TITLE
Newlines have disappeared

### ISSUE THREAD

**Issue by jethrogb** [SecUSo/privacy-friendly-notes#99] opened 2022-08-03 07:15 UTC
After a recent update from F-Droid, all the newlines from my existing notes have disappeared.

**Comment by T-vK** [comment] 2022-08-03 20:03
See #97 it's fixed in v1.1.1

**Comment by Kamuno** [comment] 2022-08-07 07:05
I'll close this issue for now. I'm really sorry this happened. Duplicate of #97

**Closed by Kamuno** 2022-08-07 07:05 UTC
Labels: bug
