### ISSUE TITLE
Export reminders too

### ISSUE THREAD

**Issue by licaon-kter** [SecUSo/privacy-friendly-notes#28] opened 2016-11-27 18:14 UTC

**Comment by Yonjuni** [comment] 2016-11-27 19:09
Is this regarding the sharing function?

**Comment by licaon-kter** [comment] 2016-11-27 19:11
Yes, and also the save function.

**Comment by Yonjuni** [comment] 2016-12-17 23:25
Belongs together https://github.com/SecUSo/privacy-friendly-notes/issues/28

**Comment by licaon-kter** [comment] 2016-12-17 23:35
Umm?

**Comment by notfoss** [comment] 2016-12-27 17:49
@licaon-kter, what Yonjuni means is that this issue should be handled with issue #33.

**Comment by Kamuno** [comment] 2019-03-08 01:19
Duplicate of #33

**Closed by Kamuno** 2019-03-08 01:19 UTC
Labels: in discussion

**Comment by T-vK** [comment] 2022-07-16 11:11
See #94
