### ISSUE TITLE
modifications lost after changing apps temporarily

### ISSUE THREAD

**Issue by carbeer** [SecUSo/privacy-friendly-notes#109] opened 2022-08-06 18:28 UTC
I made some changes to a note, switched to another app, and returned a couple of minutes later, to continue. In the meantime, my previous modifications were discarded and only the last saved state is displayed. However, I didn't close the app or the note in between, so this came as a surprise. I am using version 2.0.0.

**Comment by carbeer** [comment] 2022-08-06 18:36
I just realized that the issue was already described as part of #105. Feel free to close my issue, if you want to address both problems as one.

**Comment by Kamuno** [comment] 2022-08-07 06:41
Duplicate of #105

**Closed by Kamuno** 2022-08-07 06:41 UTC
Labels: bug
